import React from 'react'
import logo from '../../assets/trainingTips.png'
import { HealthTitle } from '../healthTip/HealthTip'

const TrainingTip = () => {
  return (
    <div className='w-full min-h-[100vh] flex items-center flex-col '>
      <div className='w-[90%] mt-[1vh] md:mt-[10vh] md:mb-[4vh] sm:shadow-[17px_9px_20.6px_-1px_rgba(0,0,0,0.25)]'>
        <HealthTitle
          Title={"TRAINING TIPS :"}
          article={"Get Yourself Ready for The Challenge! "}
        />
        <div>
          <ol className='list-decimal list-outside pl-5'>
            <img src={logo} alt="" className='sm:float-right h-[30vh]' />
            <li>{"After your warm-up, try running at an easy training pace, throwing in bursts of speed for various distances throughout the run. Vary the speed and times of the speed sections, from as short as 15 seconds to as long as 2-3 minutes. Between these bursts, allow yourself enough recovery time to match roughly 2/3 of the effort time."}</li>
            <li>{"As we get older, the need to do a proper warm-up and cool-down is paramount. Since our muscles become brittle and lose their elasticity as we grow older, the chances of injury increase dramatically. By taking 10 to 15 minutes to thoroughly warm-up your muscles before a workout, you could save yourself from months of time off due to injury. Stretching is important, but never stretch cold muscles. Before you begin your stretching routine jog lightly to warm-up your muscles."}</li>
            <li className='clear-right'>{"There are no hard and fast rules as to how to run as everyone has their own style. However, here are a few pointers to help improve your performance: Head – Look straight ahead and focus on a point 10 to 15 meters in front. Try to run in a straight line. Body – Keep your body upright with your back straight. Try not to lean, even when running up hill. Arms – Let your arms swing naturally and in rhythm with your legs while loosely cupping your hands. Feet – Naturally, the ball of the foot lands first, followed by the heel and the toes push off a fraction after that."}</li>
            <li>{"On an average day we need to drink about two liters of fluid a day to be properly hydrated. During training you will need more than this as we lose on average 500-1000ml of fluid per hour. If you exercise while dehydrated, your temperature can rise quickly and cause heatstroke, which is potentially fatal. The colour of your urine is probably the easiest indicator of fluid loss. If it’s pale and plentiful you’re well hydrated, whereas if it’s dark and sparse, you need more fluid. A loss of just 2% in your body weight may affect your ability to exercise and a 4% loss can cause exhaustion. When you are competing, for every 1% drop in body weight there’s about a 5% drop in performance."}</li>
            <li>{"Every runner has experienced a stitch – that sudden sharp pain in the side of the upper abdomen at the base of the ribs. The pain is caused by a spasm of the diaphragm. A stitch will usually go away quickly after slowing down or stopping. However, you can often make it go away by bringing your breathing into careful control during running."}</li>
            <li>{" Concentrate on belly breathing, pushing your belly out when you breathe in and relaxing it as you breathe out. Take deep breaths on the intake, and exhale suddenly, even noisily. To get the diaphragm to contract in rhythm with your steps, try to inhale and exhale as you land on your left foot. This can help prevent spasms by encouraging the diaphragm to bounce along in sync with your stride."}</li>
            <li>{"Don’t skimp on your stretching. Stretching is vital and should only be done after a full warm-up. Muscles are susceptible to injury if stretched when cold. Think of them like a cold metal bar. Try and bend it cold and it will crack, splinter or even break. However, if you warm the bar up it bends without too much effort. Cold ligaments (which stabilise joints) and tendons (which attach muscles to bones) can only be stretched when fully warmed-up."}</li>
            <li>{"Carry out ‘body scans’ during your running sessions. All you need to do is cast your mind’s eye from head to toe, looking for any signs of unnecessary tension or tightness, any muscles that could do with a stretch, and any joints that could do with loosening up. You should also try a smile – it’s impossible to be tense and smile at the same time! Try to carry out a body scan every ten to 15 minutes, to ensure you are as relaxed as possible and not wasting energy."}</li>
            <li>{" Most beginners start off by running around the block or down roads by their home but ideal places are parks, running tracks or on short cut grass. Beginners may suffer from common aches and pains such as ’shin-splints’ as a result of running on hard surfaces. If you have to run on busy roads, make sure you run facing the traffic so you can see cars coming at you."}</li>
            <li>{"It is vital that you drink plenty of fluid to avoid compromising your health. To succeed, you need to plan your drinking strategies and get into the habit of drinking, so that your body can gradually adapt to increased fluid intakes. Don’t leave it to chance; take your beverage choice with you. It is unlikely that you will drink too much water – not drinking enough is usually the problem. The only time drinking plain water may cause a problem is if you’re sweating very heavily for a prolonged period of time. In this situation, a sports drink containing sodium would be better than plain water to prevent low blood sodium levels (hyponatraemia)."}</li>
            <li>{"If you’re having a bad day and feel that another training session would be detrimental then don’t go. Training when you’re feeling unwell or having a stressful time at work for example, is counterproductive. This is not to be confused with that ‘I can’t be bothered, because I feel tired’ feeling!"}</li>
            <li>{"If you can, enter a few races before the big day. Start with maybe a 10k and then a half marathon. This will help you get used to running in the ‘event environment’ and help you with things like taking water from drinks stations and the pre-race build up. The bigger the race the better, although the first one should probably be a smaller one of a few hundred runners. Some of the big half marathons can be a great learning curve as they can have fields of many thousands and give you a real feel for what it’ll be like on marathon day."}</li>
            <li>{"If you have a bad run, don’t worry about it. You’re always going to have days when your legs feel dead or the run doesn’t go well. If this happens just cut the run short or take it easy the next day. Stay positive, in the knowledge that you’ll always have more good days than bad days."}</li>
            <li>{"Cross train, the fitter you get, the better your tolerance will be to cold weather running because your capacity to perform will have increased and that will generate more heat."}</li>
            <li>{"However, if you are truly sick of the cold the cross-training options are plentiful. You could run on a treadmill, swim, cycle, stair climb, the list goes on. To roughly work out the running equivalent of the exercise you choose, divide the time spent cross-training by the pace you would have run at the same effort level. For example, 30 minutes of cross-training is equal to about three miles at 10 minutes per mile running. It is important to remember that it is indeed possible to continue your outdoor running throughout the cold winter months and this is the best training for the race."}</li>
            <li>{"Hills are one of the most versatile of all training tools. Not only can they be used to cover all the energy pathways, they also have great variety and can be used in developing the runner’s technique. Incorporating hill work into your weekly training will help strengthen your legs and ankles. If you live in an area without hills, consider using a treadmill or stadium stairs to simulate uphill running."}</li>
            <li>{"Running in the rain – There’s really not much to running in the rain – the hardest part is getting out the door. However, here are a few tips: Be seen! Wear reflective clothing – the glimpse of the reflective glow could be the only warning a driver has that you are there. Slow down! Shorten your stride and stay relaxed. Stay warm! Staying dry will be impossible but staying warm won’t be. Get the right gear and avoid hypothermia. Don’t spin! Don’t be tempted to spin dry your trainers! Artificial heat sources contribute to the breakdown of high-tech shoe rubbers and glues."}</li>
            <li>{"It is really important to ease back and rest for any race, otherwise you won’t get the best out of yourself and you could under perform. The final week before race day should be a gradual decline in mileage and an increase in rest, recovery and sleep. Not everybody likes to have a complete rest day before they race but it is important to ease back so your body does recover and physically gets ready to perform to new heights. Work backwards from race day and plan your last four to five days like a military operation. Arrange your travel and kit well before race day, pack your bags the day before and make sure you get a couple of early nights to bank some sleep."}</li>
          </ol>
        </div>
        <p className='font-normal italic text-sm sm:text-lg leading-[24px] mb-10'>Credit: Lagos City Marathon.</p>
        </div>
    </div>
  )
}

export default TrainingTip